scan: enforce calibration file

diff --git a/demod/scan b/demod/scan
--- a/demod/scan
+++ b/demod/scan
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if ! [ -f cal ]; then
+    echo "Missing file with calibration 'cal'"
+    exit -1
+fi
+
 for S in 2464 2592 2720 2848
 do
 	START=$(( $S * 12500 + 358399864 ))
